# Generated by Django 5.0 on 2024-04-30 06:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmember',
            name='joinedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 9, 54, 57, 211965)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='payedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 9, 54, 57, 211965)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymManagement.plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 9, 54, 57, 211965)),
        ),
    ]
