# Generated by Django 5.0 on 2024-04-30 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0002_alter_gymmember_joinedat_alter_gymmember_payedat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymmember',
            name='payedAt',
        ),
        migrations.AddField(
            model_name='gymmember',
            name='paidAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 10, 11, 51, 647107)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='joinedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 10, 11, 51, 647107)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 10, 11, 51, 647107)),
        ),
    ]
