# Generated by Django 4.1.3 on 2024-04-30 16:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0007_alter_gymmember_paidat_alter_gymmember_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmember',
            name='paidAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 19, 45, 44, 318986)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymManagement.plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 19, 45, 44, 318986)),
        ),
    ]
