# Generated by Django 5.0 on 2024-04-30 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0004_alter_gymmember_joinedat_alter_gymmember_paidat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmember',
            name='joinedAt',
            field=models.DateField(default=datetime.date(2024, 4, 30)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='paidAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 10, 18, 58, 854914)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 10, 18, 58, 854746)),
        ),
    ]
