# Generated by Django 5.0 on 2024-04-30 07:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0005_alter_gymmember_joinedat_alter_gymmember_paidat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmember',
            name='paidAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 10, 42, 59, 724774)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymManagement.plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 10, 42, 59, 724163)),
        ),
    ]
