# Generated by Django 5.0 on 2024-04-30 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymManagement', '0006_alter_gymmember_paidat_alter_gymmember_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmember',
            name='paidAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 10, 48, 32, 838319)),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(0), to='gymManagement.plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 10, 48, 32, 837733)),
        ),
    ]
